---
title: "Indicators for SAC14"
author: "Haikun Xu"
date: "`r Sys.Date()`"
output:
  word_document: default
  chunk_output_type: console
---

```{r setup, include = FALSE}
year <- 2023
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r load library}
# dir <- paste0("D:/OneDrive - IATTC/Git/Indicators/",year,"/")
# setwd(dir)

library(tidyverse)
library(knitr)
library(patchwork)
```

```{r prepare the data table}
dir <- "D:/OneDrive - IATTC/Git/Indicators/2023/data/"

A71 <- read.csv(paste0(dir, "A7_old.csv"))
A72 <- read.csv(paste0(dir, "A7.csv"))

MeanW <- read.csv(paste0(dir, "average_weight.csv"))
MeanW <- MeanW %>% gather(2:9, key = "ST", value = "mean_weight") %>%
  mutate(Species = substr(ST, 1, 3),
         Type = substr(ST, 5, 8))

A7 <- rbind(A71, A72) %>%
  gather(4:6, key = "Species", value = "Catch")

A7 <- left_join(A7, MeanW) %>%
  filter(!(Type == "DEL" & Species == "BET")) %>%
  group_by(Type, Species) %>%
  mutate(
    CatchN = Catch / mean_weight,
    CPS = Catch / NSets,
    mean = 1,
    sq = ifelse(abs(Year - 2018) < 2, 1, 0),
    
    Catch2 = Catch,
    Catch2_low = quantile(Catch2, 0.1),
    Catch2_high = quantile(Catch2, 0.9),
    Catch2_sq = ifelse(Year >= 2017, sum(Catch2 * sq) / 3, NA),
    
    CatchN2 = CatchN,
    CatchN2_low = quantile(CatchN2, 0.1),
    CatchN2_high = quantile(CatchN2, 0.9),
    CatchN2_sq = ifelse(Year >= 2017, sum(CatchN2 * sq) / 3, NA),
    
    NSets2 = NSets / mean(NSets),
    NSets2_low = quantile(NSets2, 0.1),
    NSets2_high = quantile(NSets2, 0.9),
    NSets2_sq = ifelse(Year >= 2017, sum(NSets2 * sq) / 3, NA),
    
    CPS2 = CPS / mean(CPS),
    CPS2_low = quantile(CPS2, 0.1),
    CPS2_high = quantile(CPS2, 0.9),
    CPS2_sq = ifelse(Year >= 2017, sum(CPS2 * sq) / 3, NA)
  )
```

```{r Figure 2a}
# catch adjustment for 2020 and 2021
A7_catch_adjust <- A7 %>% filter(Year %in% c(2020, 2021), Type == "OBJ")

A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="BET"&A7_catch_adjust$Year==2020)] <- A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="BET"&A7_catch_adjust$Year==2020)] * (1-12/100)
A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="BET"&A7_catch_adjust$Year==2021)] <- A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="BET"&A7_catch_adjust$Year==2021)] * (1-18.2/100)

A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="YFT"&A7_catch_adjust$Year==2020)] <- A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="YFT"&A7_catch_adjust$Year==2020)] * (1+17.5/100)
A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="YFT"&A7_catch_adjust$Year==2021)] <- A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="YFT"&A7_catch_adjust$Year==2021)] * (1-9.5/100)

A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="SKJ"&A7_catch_adjust$Year==2020)] <- A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="SKJ"&A7_catch_adjust$Year==2020)] * (1-0.6/100)
A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="SKJ"&A7_catch_adjust$Year==2021)] <- A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="SKJ"&A7_catch_adjust$Year==2021)] * (1+6/100)

f2a <- ggplot(data = A7) +
  geom_line(aes(x = Year, y = Catch2)) +
  geom_point(aes(x = Year, y = Catch2)) +
  geom_point(
    aes(x = Year, y = Catch2),
    size = 2,
    color = "red",
    data = A7_catch_adjust
  ) +
  # geom_line(aes(x = Year, y = Catch2_low), linetype = "dashed") +
  # geom_line(aes(x = Year, y = Catch2_high), linetype = "dashed") +
  # geom_line(aes(x = Year, y = mean)) +
  geom_line(aes(x = Year, y = Catch2_sq), color = "red") +
  facet_grid(Species ~ Type, scales = "free") +
  theme_bw(16) +
  # coord_cartesian(ylim = c(0, 2.5)) +
  xlab("") + ylab("Catch in weight (tons)")

ggsave(f2a,
       file = "Figure2a.png",
       height = 10,
       width = 12)
```

```{r Figure 2b}
A7_catchN <- A7 %>%
  filter(!(Type == "DEL" & Species == "BET"))

A7_catchN <- left_join(A7_catchN, MeanW) %>%
  mutate(CatchN = Catch / mean_weight) %>%
  group_by(Species, Type) %>%
  mutate(
    Catch2 = CatchN,
    Catch2_low = quantile(Catch2, 0.1),
    Catch2_high = quantile(Catch2, 0.9),
    Catch2_mean = 1,
    sq = ifelse(abs(Year - 2018) < 2, 1, 0),
    Catch2_sq = ifelse(Year >= 2017, sum(Catch2 * sq) / 3, NA)
  )

# catch adjustment for 2020 and 2021
A7_catch_adjust <- A7_catchN %>% filter(Year %in% c(2020, 2021), Type == "OBJ")

A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="BET"&A7_catch_adjust$Year==2020)] <- A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="BET"&A7_catch_adjust$Year==2020)] * (1-12/100)
A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="BET"&A7_catch_adjust$Year==2021)] <- A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="BET"&A7_catch_adjust$Year==2021)] * (1-18.2/100)

A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="YFT"&A7_catch_adjust$Year==2020)] <- A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="YFT"&A7_catch_adjust$Year==2020)] * (1+17.5/100)
A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="YFT"&A7_catch_adjust$Year==2021)] <- A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="YFT"&A7_catch_adjust$Year==2021)] * (1-9.5/100)

A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="SKJ"&A7_catch_adjust$Year==2020)] <- A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="SKJ"&A7_catch_adjust$Year==2020)] * (1-0.6/100)
A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="SKJ"&A7_catch_adjust$Year==2021)] <- A7_catch_adjust$Catch2[which(A7_catch_adjust$Species=="SKJ"&A7_catch_adjust$Year==2021)] * (1+6/100)

f2b <- ggplot(data = A7_catchN) +
  geom_line(aes(x = Year, y = Catch2)) +
  geom_point(aes(x = Year, y = Catch2)) +
  geom_point(
    aes(x = Year, y = Catch2),
    size = 2,
    color = "red",
    data = A7_catch_adjust
  ) +
  # geom_line(aes(x = Year, y = Catch2_low), linetype = "dashed") +
  # geom_line(aes(x = Year, y = Catch2_high), linetype = "dashed") +
  # geom_line(aes(x = Year, y = Catch2_mean)) +
  geom_line(aes(x = Year, y = Catch2_sq), color = "red") +
  facet_grid(Species ~ Type, scales = "free") +
  theme_bw(16) +
  xlab("") + ylab("Catch in numbers (thousands of fish)")

ggsave(f2b,
       file = "Figure2b.png",
       height = 10,
       width = 12)
```