# April 8, 2023
# running this for Haikun; see last year's file for details
# NOTE: get ESTONE.txt file from Joydelee 


# ------------

# the ESTONE.txt file has the BSE estimates that form the basis for the P-S catch estimates that currently appear in the FSR tables. The file is generated by a series of SQL programs written by Alejandro Perez some years back and currently run by Nick/Joydelee

# the gear column in the ESTONE file has the following values:
# The seven different fishing "methods" (hereafter referred to as 'gears') are defined as follows:
#   1) Pole-and-line vessels
# 2, 5) Purse-seine vessels setting on schools of tuna associated with floating-objects ('small' vessels: ??? 363 mt fish-carrying capacity; 'large' vessels: > 363 mt fish-carrying capacity, respectively)
# 3, 6) Purse-seine vessels setting on unassociated schools of tuna (small and large vessels, respectively)
# 4, 7) Purse-seine vessels setting on tunas associated with dolphins (small and large vessels, respectively)
# the area column in the ESTONE file is the 13 areas used for the BSE prior to the changes to fishery definitions that we made (you can find the area map in IATTC Special Report 18)
# the W column is the estimated weight that corresponds to the BSE. Each record in the file corresponds to a unique combination of: species code x year x area x gear x mon x bin, where mon is month and bin is the 1cm length bin.
# ----------------


estone<-read.table("D:/OneDrive - IATTC/IATTC/2024/SAC15/PS Database/ESTONE.txt",header=F,sep=",")
names(estone)<-c("species","year","area","gear","mon","TN","TW","bin","N","W")


# Average length
# according to Alejandro's documentation, the column bin in teh ESTONE file is most likely the lower edge of the 1-cm bin

estone$bin.midpt<-estone$bin+0.5

# DEL sets
# YFT
# count number fish by 1 cm bin x year
tmpcl<-tapply(estone$N[(estone$gear==7 | estone$gear==4) & estone$species==110],list(estone$bin.midpt[(estone$gear==7 | estone$gear==4) & estone$species==110],estone$year[(estone$gear==7 | estone$gear==4) & estone$species==110]),sum)

# set NAs to 0
tmpcl[is.na(tmpcl)]<-0

# get 1-cm bins 
tmpclx<-as.numeric(dimnames(tmpcl)[[1]])

# get total number of fish per 1cm bin
tmpclz<-t(tmpclx)%*%tmpcl

# get average length by year
tmpclyft.del<-tmpclz/apply(tmpcl,2,sum)


# SKJ
# count number fish by 1 cm bin x year
tmpcl<-tapply(estone$N[(estone$gear==7 | estone$gear==4) & estone$species==111],list(estone$bin.midpt[(estone$gear==7 | estone$gear==4) & estone$species==111],estone$year[(estone$gear==7 | estone$gear==4) & estone$species==111]),sum)

# set NAs to 0
tmpcl[is.na(tmpcl)]<-0

# get 1-cm bins 
tmpclx<-as.numeric(dimnames(tmpcl)[[1]])

# get total number of fish per 1cm bin
tmpclz<-t(tmpclx)%*%tmpcl

# get average length by year
tmpclskj.del<-tmpclz/apply(tmpcl,2,sum)



# UNA sets
# BET
# count number fish by 1 cm bin x year
tmpcl<-tapply(estone$N[(estone$gear==3 | estone$gear==6) & estone$species==106],list(estone$bin.midpt[(estone$gear==3 | estone$gear==6) & estone$species==106],estone$year[(estone$gear==3 | estone$gear==6) & estone$species==106]),sum)

# set NAs to 0
tmpcl[is.na(tmpcl)]<-0

# get 1-cm bins 
tmpclx<-as.numeric(dimnames(tmpcl)[[1]])

# get total number of fish per 1cm bin
tmpclz<-t(tmpclx)%*%tmpcl

# get average length by year
tmpclbet.una<-tmpclz/apply(tmpcl,2,sum)


# YFT
# count number fish by 1 cm bin x year
tmpcl<-tapply(estone$N[(estone$gear==3 | estone$gear==6) & estone$species==110],list(estone$bin.midpt[(estone$gear==3 | estone$gear==6) & estone$species==110],estone$year[(estone$gear==3 | estone$gear==6) & estone$species==110]),sum)

# set NAs to 0
tmpcl[is.na(tmpcl)]<-0

# get 1-cm bins 
tmpclx<-as.numeric(dimnames(tmpcl)[[1]])

# get total number of fish per 1cm bin
tmpclz<-t(tmpclx)%*%tmpcl

# get average length by year
tmpclyft.una<-tmpclz/apply(tmpcl,2,sum)


# SKJ
# count number fish by 1 cm bin x year
tmpcl<-tapply(estone$N[(estone$gear==3 | estone$gear==6) & estone$species==111],list(estone$bin.midpt[(estone$gear==3 | estone$gear==6) & estone$species==111],estone$year[(estone$gear==3 | estone$gear==6) & estone$species==111]),sum)

# set NAs to 0
tmpcl[is.na(tmpcl)]<-0

# get 1-cm bins 
tmpclx<-as.numeric(dimnames(tmpcl)[[1]])

# get total number of fish per 1cm bin
tmpclz<-t(tmpclx)%*%tmpcl

# get average length by year
tmpclskj.una<-tmpclz/apply(tmpcl,2,sum)



# OBJ sets
# BET
# count number fish by 1 cm bin x year
tmpcl<-tapply(estone$N[(estone$gear==2 | estone$gear==5) & estone$species==106],list(estone$bin.midpt[(estone$gear==2 | estone$gear==5) & estone$species==106],estone$year[(estone$gear==2 | estone$gear==5) & estone$species==106]),sum)

# set NAs to 0
tmpcl[is.na(tmpcl)]<-0

# get 1-cm bins 
tmpclx<-as.numeric(dimnames(tmpcl)[[1]])

# get total number of fish per 1cm bin
tmpclz<-t(tmpclx)%*%tmpcl

# get average length by year
tmpclbet.obj<-tmpclz/apply(tmpcl,2,sum)

# YFT
# count number fish by 1 cm bin x year
tmpcl<-tapply(estone$N[(estone$gear==2 | estone$gear==5) & estone$species==110],list(estone$bin.midpt[(estone$gear==2 | estone$gear==5) & estone$species==110],estone$year[(estone$gear==2 | estone$gear==5) & estone$species==110]),sum)

# set NAs to 0
tmpcl[is.na(tmpcl)]<-0

# get 1-cm bins 
tmpclx<-as.numeric(dimnames(tmpcl)[[1]])

# get total number of fish per 1cm bin
tmpclz<-t(tmpclx)%*%tmpcl

# get average length by year
tmpclyft.obj<-tmpclz/apply(tmpcl,2,sum)

# SKJ
# count number fish by 1 cm bin x year
tmpcl<-tapply(estone$N[(estone$gear==2 | estone$gear==5) & estone$species==111],list(estone$bin.midpt[(estone$gear==2 | estone$gear==5) & estone$species==111],estone$year[(estone$gear==2 | estone$gear==5) & estone$species==111]),sum)

# set NAs to 0
tmpcl[is.na(tmpcl)]<-0

# get 1-cm bins 
tmpclx<-as.numeric(dimnames(tmpcl)[[1]])

# get total number of fish per 1cm bin
tmpclz<-t(tmpclx)%*%tmpcl

# get average length by year
tmpclskj.obj<-tmpclz/apply(tmpcl,2,sum)

write.csv(
  cbind(
    seq(2000, 2023),
    as.vector(tmpclyft.del),
    as.vector(tmpclskj.del),
    as.vector(tmpclbet.una),
    as.vector(tmpclyft.una),
    as.vector(tmpclskj.una),
    as.vector(tmpclbet.obj),
    as.vector(tmpclyft.obj),
    as.vector(tmpclskj.obj)
  ),
  file = "D:/OneDrive - IATTC/Git/Indicators/2024/data/average length_yr x setype_2000-2022.csv",
  row.names = FALSE
)


#
# Average weight
# DEL sets
tmp.w<-tapply(estone$W[(estone$gear==4 | estone$gear==7)],list(estone$year[(estone$gear==4 | estone$gear==7)],estone$species[(estone$gear==4 | estone$gear==7)]),sum)

tmp.n<-tapply(estone$N[(estone$gear==4 | estone$gear==7)],list(estone$year[(estone$gear==4 | estone$gear==7)],estone$species[(estone$gear==4 | estone$gear==7)]),sum)

tmp.del<-1000*tmp.w/tmp.n

tmp.del[is.na(tmp.del)]<-0


# UNA sets
tmp.w<-tapply(estone$W[(estone$gear==3 | estone$gear==6)],list(estone$year[(estone$gear==3 | estone$gear==6)],estone$species[(estone$gear==3 | estone$gear==6)]),sum)

tmp.n<-tapply(estone$N[(estone$gear==3 | estone$gear==6)],list(estone$year[(estone$gear==3 | estone$gear==6)],estone$species[(estone$gear==3 | estone$gear==6)]),sum)

tmp.una<-1000*tmp.w/tmp.n

tmp.una[is.na(tmp.una)]<-0


# OBJ sets
tmp.w<-tapply(estone$W[(estone$gear==2 | estone$gear==5)],list(estone$year[(estone$gear==2 | estone$gear==5)],estone$species[(estone$gear==2 | estone$gear==5)]),sum)

tmp.n<-tapply(estone$N[(estone$gear==2 | estone$gear==5)],list(estone$year[(estone$gear==2 | estone$gear==5)],estone$species[(estone$gear==2 | estone$gear==5)]),sum)

tmp.obj<-1000*tmp.w/tmp.n

tmp.obj[is.na(tmp.obj)]<-0

write.csv(cbind(seq(2000, 2023), tmp.del[, 2:3], tmp.una, tmp.obj),
          file = "D:/OneDrive - IATTC/Git/Indicators/2024/data/average weight_yr x setype_2000-2022.csv",
          row.names = FALSE)